name: Ruff
on: 
    push:
        branches:
            - main
        paths:
          - '.github/workflows/ruff.yml'
          - 'ruff.toml'
          - '**.py'
    pull_request:
        branches:
            - main
        paths:
            - '.github/workflows/ruff.yml'
            - 'ruff.toml'
            - '**.py'
    workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1
